### ISSUE TITLE
Can't cast unless I update the Google Play services

### ISSUE THREAD

**Issue by MxRay** [YTVanced/VancedMicroG#129] opened 2021-05-01 19:02 UTC
After the latest update of the MicroG (0.2.18.2105) whenever I try to cast the notification will pop up saying: 
"YouTube Vanced won't run unless you update Google Play services."
Clicking on this notification leads me to infinite loading in Google Play.

Phone: Sony Xperia 5 II
OS: Android 11 (58.1.A.5.159)
Manager: 2.6
Vanced: 16.16.38
Google Play: 25.1.24-21

**Comment by KevinX8** [comment] 2021-05-01 19:27
Duplicate of #688

**Closed by KevinX8** 2021-05-01 19:27 UTC
