### ISSUE TITLE
Notification Spam Loop

### ISSUE THREAD

**Issue by EL-STINKO** [YTVanced/VancedMicroG#166] opened 2021-11-28 21:45 UTC
As of lately the bug randomly started out of seemingly no where and the only fix is for me to uninstall microG and reinstall it. I now no longer get notifications until I randomly get one amongst a spam of multiple other notifications constantly being sent in a loop.

**Comment by milindgoel15** [comment] 2021-12-16 07:52
Duplicate of [#1107](https://github.com/YTVanced/Vanced/issues/1107)

**Closed by milindgoel15** 2021-12-16 07:52 UTC
