### ISSUE TITLE
YouTube vanced issue

### ISSUE THREAD

**Issue by Wkwkland45** [YTVanced/VancedMicroG#163] opened 2021-10-07 18:22 UTC
I have an issue when I want to download offline videos on YouTube, I can't download videos with 720p resolution and can't open the links on YouTube vanced

The cell phone that I'm currently using is: XIAOMI REDMI NOTE 10 android 11, miui 12.5.1
![Screenshot_2021-10-08-01-12-54-067_com vanced android youtube](https://user-images.githubusercontent.com/92117613/136441138-8544b7aa-44e8-48e9-8b59-06a7e9cd1e58.jpg)
![Screenshot_2021-10-08-01-13-29-819_com vanced android youtube](https://user-images.githubusercontent.com/92117613/136441147-1750a7d3-7c71-4e86-bfa1-4a063c90f98c.jpg)

**Comment by milindgoel15** [comment] 2021-10-09 04:04
Duplicate of https://github.com/YTVanced/Vanced/issues/1317

**Closed as completed** 2021-10-09 04:05 UTC
